services:
  scrapper_app:
    image: hub.inf.pucp.edu.pe/scrapper:latest
    container_name: scrapper_app
    restart: unless-stopped
    env_file: .env.scrapper-dp2
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy_vm2
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - scrapper_app
