version: "3.9"

services:
  frontend:
    build: ./front-dp2
    restart: unless-stopped

  backend:
    build: ./back-dp2
    env_file:
      - ./back-dp2/.env
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - database
    ports:
      - "8000:8000"

  proxy:
    image: nginx:stable
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "{{ rabbitmq_user }}"
      RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_password }}"
    ports:
      - "15672:15672"

  database:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: "{{ mysql_database_name }}"
      MARIADB_USER: "{{ mysql_user }}"
      MARIADB_PASSWORD: "{{ mysql_password }}"
      MARIADB_ROOT_PASSWORD: "{{ mysql_password }}"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
